apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "javaanalyzer.fullname" . }}
  labels:
    {{- include "javaanalyzer.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "javaanalyzer.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "javaanalyzer.name" . }}
    spec:
      containers:
        - name: javaanalyzer
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: {{ include "javaanalyzer.fullname" . }}-config
            - secretRef:
            name: {{ include "javaanalyzer.fullname" . }}-secret
