apiVersion: v1
kind: Service
metadata:
  name: {{ include "javaanalyzer.fullname" . }}
  labels:
    {{- include "javaanalyzer.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      nodePort: {{ .Values.service.nodePort | default 30080 }}
  selector:
    app: {{ include "javaanalyzer.name" . }}